version: '3.8'

services:
  django:
    build: .
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes

  celery:
    build: .
    restart: on-failure
    command: celery -A notifications worker -l info -E
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - django
  dashboard:
      container_name: dashboard
      build: .
      command: celery --app=notifications flower --port=5555 broker=redis://redis:6379/0
      ports:
        - 5555:5555
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
      depends_on:
        - redis
        - django
        - celery
